### ISSUE TITLE
Roadmap to 4.0.0

### ISSUE THREAD

**Issue by nessthehero** [BarkleyREI/generator-brei-app#211]
_From @nessthehero on December 1, 2016 19:16_

We need to document what features we need from the current generator in the gulp generator, and what new features we want.

For example, we'll want to switch to a postcss approach for autoprefixing and maybe cssnano for minification, instead of just migrating over autoprefixer and cssmin.

## Prerequisites before development
- [x] Release version 3.2.0 of Grunt generator to fix all current issues and critical feature requests.
- [ ] Add features to stabilize 3.x path so that it can continue to exist.
- [ ] Update documentation on Grunt generator and related repos.

## Feature List
- [x] Modernizr 3.x Custom Build
- [x] GUI Menu to select sub-generator task
- [x] Handlebars/Templating Language build into static pages
- [x] Minify JS
- [x] Babel/ES6 translation
- [x] Minify CSS
- [x] Autoprefix CSS

cc: @Sean-BREI 

_Copied from original issue: BarkleyREI/generator-brei-gulp#1_

**Comment by nessthehero** [comment]
I'm going to update my top comment with any tasks we need to accomplish before we can kick off this generator, and I also want to document the full feature list of the generator so that we capture everything. Every little thing the generator does, I want to document. E.g. "Builds handlebar files into static pages", "Shows helpful menu on initialization", etc.

**Comment by nessthehero** [comment]
We might consider something other than Assemble for the templates.

I would highly prefer something that already uses handlebars so that we can migrate existing templates, but I am open to using something like Jade.

**Comment by nessthehero** [comment]
[BarkleyREI/experimental-brei-app](https://github.com/BarkleyREI/experimental-brei-app)

**Comment by nessthehero** [comment]
We're at 4.0.0. Merry Christmas.
